### PR TITLE
adding apt-get clean to the dockerfiles

### PR DESCRIPTION
**Pull request by ghost**
Well, I rearranged stuff for clarity. When using too much `apt-get install`, it's a mess to track what is installed and what isn't. Otherwise, the only thing I did was to add `apt-get clean`, because the source for Rubinius is already cleaned up.

### CODE REVIEW

**Comment by ghost** [comment]
@brixen ok, that's done. Now it just performs an `apt-get remove --purge` and `apt-get autoremove --purge` once it compiles Rubinius. However, one must [squash the resulting image](http://jasonwilder.com/blog/2014/08/19/squashing-docker-images/). I don't know how to do this using the Docker Hub, but will give it a try tomorrow.

If anyone else has thoughts on this, please ping me! It would be nice to find a solution :)

All the best and have a wonderful year.

**Comment by ghost** [comment]
Still a WIP, though getting closer.

The best way to get rid of compilers is to bundle binaries instead. The resulting image is just 204.5 MB, which is much better than the previous 666.5 MB.

Added a Makefile to ease the process of downloading binaries, uncompressing and adding stuff. Basically, **make** will create an image named `rubinius-3.0-on-wily` (for 15.10) or `rubinius-3.0-on-trusty` (for 14.04).

**Comment by ghost** [comment]
Finally! :smiley:

This is the output of `docker images`:

``` bash
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
rubinius-3.0-on-trusty   latest              1243a81899a0        3 minutes ago       279 MB
rubinius-3.0-on-wily     latest              c05bb69a0977        4 minutes ago       224.9 MB
docker.io/ubuntu         15.10               2804d41e7f10        3 weeks ago         133.5 MB
docker.io/ubuntu         14.04               89d5d8e8bafb        3 weeks ago         187.9 MB
```

This is what happens when I run `docker run -it --rm rubinius-3.0-on-trusty:

``` bash
root@db72da665d93:/# ruby -v
rubinius 3.0 (2.1.0 e946d9a7 2016-01-01 3.4.2 JI) [x86_64-linux-gnu]
```

This is what happens when I run `docker run -it --rm rubinius-3.0-on-wily:

``` bash
root@53cdbdd3c73c:/# ruby -v
rubinius 3.0 (2.1.0 e946d9a7 2016-01-01 3.4.2 JI) [x86_64-linux-gnu]
```

The `Dockerfiles` now don't depend on the `Makefile` to run, and the image size has decreased greatly without the need for squashing. I might need a couple :eyes: here, in case there is a better URL for retrieving the binaries for Rubinius.

As for using `FROM scratch` and `FROM busybox`: my first attempt was to get rid of Ubuntu entirely and copying the contents of rubinius.tar.bz2 directly on a scratch machine, and then on a busybox machine. Neither worked, but I cannot explain why.

@brixen: ready to be merged.

**Comment by brixen** [comment]
@spicymagpie awesome, thanks! I was planning to use the binary builds eventually, so this is perfect!

I'll merge this and then I need to add gems/bin to PATH. Then I'll copy these over to https://github.com/rubinius/rubinius.

**Pull request merged**
